version: '3.8'

services:
  drugfacts-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: drugfacts-wiki-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - drugfacts-network

  # Database removed - not needed for static Next.js app

networks:
  drugfacts-network:
    driver: bridge