version: '3.8'

services:
  # MongoDB Database for development
  mongodb:
    image: mongo:7.0
    container_name: drugfacts-mongodb-dev
    environment:
      MONGO_INITDB_DATABASE: drug_facts
    volumes:
      - mongodb_dev_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - drugfacts-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Database seeder service for development
  db-seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    container_name: drugfacts-seeder-dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=drug_facts
      - MONGODB_COLLECTION_NAME=drugs
    volumes:
      - ./data/drugs:/app/data
      - ./hardened_mongo_import.py:/app/hardened_mongo_import.py
      - ./drug_label_schema.yaml:/app/drug_label_schema.yaml
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    restart: "no"
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        echo 'Starting database seeding...' &&
        python hardened_mongo_import.py -j /app/data/Labels.json -s /app/drug_label_schema.yaml --mongo-uri mongodb://mongodb:27017/ --db-name drug_facts --collection-name drugs -v &&
        echo 'Database seeding completed!'
      "

  # MongoDB Express for database management (development only)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: drugfacts-mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    restart: unless-stopped

volumes:
  mongodb_dev_data:

networks:
  drugfacts-dev-network:
    driver: bridge