version: '3.8'

services:
  drugfacts-app:
    build: .
    container_name: drugfacts-wiki
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - drugfacts-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database (removed - not needed for static Next.js app)
  # Redis (removed - not needed for static Next.js app)

  # Nginx reverse proxy (optional, for production deployment with SSL)
  nginx:
    image: nginx:alpine
    container_name: drugfacts-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - drugfacts-app
    restart: unless-stopped
    networks:
      - drugfacts-network

networks:
  drugfacts-network:
    driver: bridge