version: '3.8'

services:
  drugfacts-app:
    build: .
    container_name: drugfacts-wiki
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Database configuration (if using PostgreSQL in the future)
      # - DATABASE_URL=postgresql://username:password@db:5432/drugfacts
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - drugfacts-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database (optional, for future database integration)
  db:
    image: postgres:15-alpine
    container_name: drugfacts-postgres
    environment:
      POSTGRES_DB: drugfacts
      POSTGRES_USER: drugfacts_user
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - drugfacts-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drugfacts_user -d drugfacts"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis (optional, for session storage and caching)
  redis:
    image: redis:7-alpine
    container_name: drugfacts-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - drugfacts-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Nginx reverse proxy (optional, for production deployment)
  nginx:
    image: nginx:alpine
    container_name: drugfacts-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - drugfacts-app
    restart: unless-stopped
    networks:
      - drugfacts-network

volumes:
  postgres_data:
  redis_data:

networks:
  drugfacts-network:
    driver: bridge