version: '3.8'

services:
  # Next.js Frontend Service for development
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: development
    container_name: drugfacts-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    command: npm run dev

  # NestJS Backend Service for development
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: development
    container_name: drugfacts-backend-dev
    ports:
      - "3001:3001"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=drug_facts
      - FRONTEND_URL=http://frontend:3000
    volumes:
      - ./backend/drugfacts-api:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    command: npm run start:dev

  # MongoDB Database for development
  mongodb:
    image: mongo:7.0
    container_name: drugfacts-mongodb-dev
    environment:
      MONGO_INITDB_DATABASE: drug_facts
    volumes:
      - mongodb_dev_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - drugfacts-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Database seeder service for development (basic)
  db-seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    container_name: drugfacts-seeder-dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=drug_facts
      - MONGODB_COLLECTION_NAME=drugs
    volumes:
      - ./data/drugs:/app/data
      - ./hardened_mongo_import.py:/app/hardened_mongo_import.py
      - ./drug_label_schema.yaml:/app/drug_label_schema.yaml
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    restart: "no"
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        echo 'Starting database seeding...' &&
        python hardened_mongo_import.py -j /app/data/Labels.json -s /app/drug_label_schema.yaml --mongo-uri mongodb://mongodb:27017/ --db-name drug_facts --collection-name drugs -v &&
        echo 'Database seeding completed!'
      "
    profiles: ["basic-seeder"]

  # AI-enhanced database seeder service for development
  ai-seeder:
    build:
      context: .
      dockerfile: Dockerfile.ai-seeder
    container_name: drugfacts-ai-seeder-dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=drug_facts
      - MONGODB_COLLECTION_NAME=drugs
      - ENABLE_AI_CLASSIFICATION=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENPIPE_API_KEY=${OPENPIPE_API_KEY}
      - AI_LOG_LEVEL=DEBUG
    volumes:
      - ./data/drugs:/app/data
      - ./logs:/app/logs
      - ./ai_classification:/app/ai_classification
      - ./hardened_mongo_import.py:/app/hardened_mongo_import.py
      - ./enhanced_drug_importer.py:/app/enhanced_drug_importer.py
      - ./run_enhanced_import.py:/app/run_enhanced_import.py
      - ./drug_label_schema.yaml:/app/drug_label_schema.yaml
      - ./drug_label_extracation_system_prompt.md:/app/drug_label_extracation_system_prompt.md
      - ./.env:/app/.env:ro
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    restart: "no"
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        echo 'Starting AI-enhanced database seeding...' &&
        python run_enhanced_import.py -v &&
        echo 'AI-enhanced database seeding completed!'
      "
    profiles: ["ai-seeder"]

  # MongoDB Express for database management (development only)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: drugfacts-mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drugfacts-dev-network
    restart: unless-stopped

volumes:
  mongodb_dev_data:

networks:
  drugfacts-dev-network:
    driver: bridge