version: '3.8'

services:
  drugfacts-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: drugfacts-wiki-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - drugfacts-network

  # Development database
  db:
    image: postgres:15-alpine
    container_name: drugfacts-postgres-dev
    environment:
      POSTGRES_DB: drugfacts_dev
      POSTGRES_USER: drugfacts_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - drugfacts-network

volumes:
  postgres_dev_data:

networks:
  drugfacts-network:
    driver: bridge